language: python

python:
    - "3.4"

cache:
  directories:
    - cache

before_install:
    - sudo apt-get update


install:
    - sudo pip install pelican markdown

script:
    - git clone --depth 1 https://github.com/Bekcpear/bekcpear.github.io output
    - make html
